### ISSUE TITLE
[问题]文档图片被ban

### ISSUE THREAD

**Issue by misaka10843** [muxigame/GalForUnity#3]
首先先感谢大佬能制作出这么好的插件！

但是在文档网站中，很多的图片都已经被度吧ban了，如下图

![image](https://user-images.githubusercontent.com/69132853/191915789-cc714b49-e386-47ab-80f9-88218c70d382.png)

请问能否修复以下？（虽然可能也没啥影响www）

**Comment by muxigame** [comment]
现在捉急做2.0，暂时没有维护稳定，文档会随着2.0版同步更新，届时文档图片会使用第三方外链服务代替

**Comment by misaka10843** [comment]
> 现在捉急做2.0，暂时没有维护稳定，文档会随着2.0版同步更新，届时文档图片会使用第三方外链服务代替

希望大佬能尽快做出2.0qwq
加油！
